name: "Nuki Code Review Action"
description: "Nuki reviews new pull requests"
branding:
  icon: "book-open"
  color: "blue"
inputs:
  OPENAI_API_KEY:
    description: "OpenAI API Key"
    required: true
  GITHUB_APP_PRIVATE_KEY:
    description: "GitHub App Private Key"
    required: true
runs:
  using: "node20"
  main: "src/index.js"
